### PR TITLE
new reluctant service override with changes

### PR DESCRIPTION
**Pull request by lawrence-lee**

### CODE REVIEW

**Comment by jhinkey** [comment]
Merged locally. Started reviewing.

**Comment by jhinkey** [comment]
Merged locally. Working on this now. thanks.

**Comment by jhinkey** [comment]
Hey Lawrence, with the number of changes I needed to make reorganizing things and in light of the switch from liferay-gradle to gradle folders, I've created a new branch--but it doesn't have any of your commits.

This PR is superceded by https://github.com/lawrence-lee/liferay-blade-samples/pull/19

**Comment by jhinkey** [comment]
@lawrence-lee Let me know if it's OK to delete my branch in which I merged your commits. Thanks.

**Comment by lawrence-lee** [comment]
@jhinkey thanks for sending the PR. I'll be able to review with Greg probably tomorrow.

**Pull request closed without merging**
